/* =========================================================
   countries.js — country metadata keyed by ISO 3166-1
   numeric code (matches the world-atlas TopoJSON IDs).
   Population in millions (approx, for simulation purposes).
   ========================================================= */

const COUNTRIES = {
    // --- AFRICA ---
    '012': { name:'Algeria',     continent:'africa', culture:'middle_eastern',  pop:45,   lat:28,   lon:2,    tz:1,    aliases:['algeria','algerian'] },
    '024': { name:'Angola',      continent:'africa', culture:'african_west',    pop:34,   lat:-12,  lon:18,   tz:1,    aliases:['angola'] },
    '072': { name:'Botswana',    continent:'africa', culture:'african_south',   pop:2,    lat:-22,  lon:24,   tz:2,    aliases:['botswana'] },
    '854': { name:'Burkina Faso',continent:'africa', culture:'african_west',    pop:22,   lat:12,   lon:-1,   tz:0,    aliases:['burkina','burkina faso'] },
    '108': { name:'Burundi',     continent:'africa', culture:'african_east',    pop:13,   lat:-3,   lon:30,   tz:2,    aliases:['burundi'] },
    '120': { name:'Cameroon',    continent:'africa', culture:'african_west',    pop:27,   lat:6,    lon:12,   tz:1,    aliases:['cameroon'] },
    '140': { name:'Central African Republic', continent:'africa', culture:'african_west', pop:5, lat:6, lon:21, tz:1, aliases:['car','central african republic','central africa'] },
    '148': { name:'Chad',        continent:'africa', culture:'african_west',    pop:17,   lat:15,   lon:19,   tz:1,    aliases:['chad'] },
    '180': { name:'DR Congo',    continent:'africa', culture:'african_west',    pop:99,   lat:-2,   lon:23,   tz:1,    aliases:['congo','dr congo','drc','democratic republic of congo'] },
    '178': { name:'Congo',       continent:'africa', culture:'african_west',    pop:5,    lat:-1,   lon:15,   tz:1,    aliases:['republic of congo','congo-brazzaville'] },
    '384': { name:'Ivory Coast', continent:'africa', culture:'african_west',    pop:28,   lat:8,    lon:-5,   tz:0,    aliases:['ivory coast',"côte d'ivoire",'cote divoire','cote d ivoire'] },
    '262': { name:'Djibouti',    continent:'africa', culture:'african_east',    pop:1,    lat:12,   lon:43,   tz:3,    aliases:['djibouti'] },
    '818': { name:'Egypt',       continent:'africa', culture:'middle_eastern',  pop:110,  lat:27,   lon:30,   tz:2,    aliases:['egypt','egyptian','cairo','nile'] },
    '231': { name:'Ethiopia',    continent:'africa', culture:'african_east',    pop:126,  lat:9,    lon:40,   tz:3,    aliases:['ethiopia','ethiopian','addis'] },
    '232': { name:'Eritrea',     continent:'africa', culture:'african_east',    pop:4,    lat:15,   lon:39,   tz:3,    aliases:['eritrea'] },
    '266': { name:'Gabon',       continent:'africa', culture:'african_west',    pop:2,    lat:-1,   lon:11,   tz:1,    aliases:['gabon'] },
    '288': { name:'Ghana',       continent:'africa', culture:'african_west',    pop:34,   lat:8,    lon:-1,   tz:0,    aliases:['ghana','ghanaian'] },
    '324': { name:'Guinea',      continent:'africa', culture:'african_west',    pop:14,   lat:10,   lon:-10,  tz:0,    aliases:['guinea'] },
    '404': { name:'Kenya',       continent:'africa', culture:'african_east',    pop:55,   lat:1,    lon:38,   tz:3,    aliases:['kenya','kenyan','nairobi'] },
    '426': { name:'Lesotho',     continent:'africa', culture:'african_south',   pop:2,    lat:-29,  lon:28,   tz:2,    aliases:['lesotho'] },
    '430': { name:'Liberia',     continent:'africa', culture:'african_west',    pop:5,    lat:6,    lon:-9,   tz:0,    aliases:['liberia'] },
    '434': { name:'Libya',       continent:'africa', culture:'middle_eastern',  pop:7,    lat:27,   lon:17,   tz:2,    aliases:['libya'] },
    '450': { name:'Madagascar',  continent:'africa', culture:'african_east',    pop:30,   lat:-19,  lon:47,   tz:3,    aliases:['madagascar'] },
    '454': { name:'Malawi',      continent:'africa', culture:'african_east',    pop:21,   lat:-13,  lon:34,   tz:2,    aliases:['malawi'] },
    '466': { name:'Mali',        continent:'africa', culture:'african_west',    pop:22,   lat:17,   lon:-4,   tz:0,    aliases:['mali'] },
    '478': { name:'Mauritania',  continent:'africa', culture:'middle_eastern',  pop:5,    lat:20,   lon:-10,  tz:0,    aliases:['mauritania'] },
    '504': { name:'Morocco',     continent:'africa', culture:'middle_eastern',  pop:38,   lat:32,   lon:-6,   tz:1,    aliases:['morocco','moroccan','marrakech','casablanca'] },
    '508': { name:'Mozambique',  continent:'africa', culture:'african_east',    pop:33,   lat:-18,  lon:35,   tz:2,    aliases:['mozambique'] },
    '516': { name:'Namibia',     continent:'africa', culture:'african_south',   pop:3,    lat:-22,  lon:17,   tz:2,    aliases:['namibia'] },
    '562': { name:'Niger',       continent:'africa', culture:'african_west',    pop:26,   lat:17,   lon:8,    tz:1,    aliases:['niger'] },
    '566': { name:'Nigeria',     continent:'africa', culture:'african_west',    pop:223,  lat:10,   lon:8,    tz:1,    aliases:['nigeria','nigerian','lagos','abuja'] },
    '646': { name:'Rwanda',      continent:'africa', culture:'african_east',    pop:14,   lat:-2,   lon:30,   tz:2,    aliases:['rwanda'] },
    '686': { name:'Senegal',     continent:'africa', culture:'african_west',    pop:17,   lat:14,   lon:-15,  tz:0,    aliases:['senegal','dakar'] },
    '694': { name:'Sierra Leone',continent:'africa', culture:'african_west',    pop:8,    lat:8,    lon:-12,  tz:0,    aliases:['sierra leone'] },
    '706': { name:'Somalia',     continent:'africa', culture:'african_east',    pop:17,   lat:6,    lon:46,   tz:3,    aliases:['somalia'] },
    '710': { name:'South Africa',continent:'africa', culture:'african_south',   pop:61,   lat:-29,  lon:24,   tz:2,    aliases:['south africa','south african','cape town','johannesburg','jozi'] },
    '728': { name:'South Sudan', continent:'africa', culture:'african_east',    pop:11,   lat:7,    lon:31,   tz:3,    aliases:['south sudan'] },
    '729': { name:'Sudan',       continent:'africa', culture:'middle_eastern',  pop:48,   lat:15,   lon:30,   tz:2,    aliases:['sudan','sudanese','khartoum'] },
    '834': { name:'Tanzania',    continent:'africa', culture:'african_east',    pop:66,   lat:-6,   lon:35,   tz:3,    aliases:['tanzania','tanzanian','zanzibar','kilimanjaro'] },
    '768': { name:'Togo',        continent:'africa', culture:'african_west',    pop:9,    lat:8,    lon:1,    tz:0,    aliases:['togo'] },
    '788': { name:'Tunisia',     continent:'africa', culture:'middle_eastern',  pop:12,   lat:34,   lon:9,    tz:1,    aliases:['tunisia'] },
    '800': { name:'Uganda',      continent:'africa', culture:'african_east',    pop:48,   lat:1,    lon:32,   tz:3,    aliases:['uganda','ugandan'] },
    '894': { name:'Zambia',      continent:'africa', culture:'african_south',   pop:20,   lat:-13,  lon:28,   tz:2,    aliases:['zambia'] },
    '716': { name:'Zimbabwe',    continent:'africa', culture:'african_south',   pop:16,   lat:-19,  lon:30,   tz:2,    aliases:['zimbabwe'] },

    // --- AMERICAS ---
    '032': { name:'Argentina',   continent:'americas', culture:'latin_american', pop:46,  lat:-35,  lon:-65,  tz:-3,   aliases:['argentina','argentinian','buenos aires','patagonia'] },
    '068': { name:'Bolivia',     continent:'americas', culture:'latin_american', pop:12,  lat:-17,  lon:-65,  tz:-4,   aliases:['bolivia','la paz'] },
    '076': { name:'Brazil',      continent:'americas', culture:'latin_american', pop:216, lat:-10,  lon:-55,  tz:-3,   aliases:['brazil','brasil','brazilian','rio','rio de janeiro','sao paulo','são paulo','amazon'] },
    '124': { name:'Canada',      continent:'americas', culture:'north_american', pop:39,  lat:57,   lon:-106, tz:-5,   aliases:['canada','canadian','toronto','vancouver','quebec','ontario'] },
    '152': { name:'Chile',       continent:'americas', culture:'latin_american', pop:20,  lat:-33,  lon:-71,  tz:-4,   aliases:['chile','chilean','santiago','patagonia'] },
    '170': { name:'Colombia',    continent:'americas', culture:'latin_american', pop:52,  lat:4,    lon:-74,  tz:-5,   aliases:['colombia','colombian','bogota','bogotá','medellin'] },
    '188': { name:'Costa Rica',  continent:'americas', culture:'latin_american', pop:5,   lat:10,   lon:-84,  tz:-6,   aliases:['costa rica'] },
    '192': { name:'Cuba',        continent:'americas', culture:'latin_american', pop:11,  lat:22,   lon:-78,  tz:-5,   aliases:['cuba','cuban','havana'] },
    '214': { name:'Dominican Republic', continent:'americas', culture:'latin_american', pop:11, lat:19, lon:-70, tz:-4, aliases:['dominican republic','dominican'] },
    '218': { name:'Ecuador',     continent:'americas', culture:'latin_american', pop:18,  lat:-1,   lon:-78,  tz:-5,   aliases:['ecuador','galapagos'] },
    '320': { name:'Guatemala',   continent:'americas', culture:'latin_american', pop:18,  lat:15,   lon:-90,  tz:-6,   aliases:['guatemala'] },
    '332': { name:'Haiti',       continent:'americas', culture:'latin_american', pop:12,  lat:19,   lon:-72,  tz:-5,   aliases:['haiti','haitian','port-au-prince'] },
    '340': { name:'Honduras',    continent:'americas', culture:'latin_american', pop:11,  lat:15,   lon:-86,  tz:-6,   aliases:['honduras'] },
    '484': { name:'Mexico',      continent:'americas', culture:'latin_american', pop:128, lat:23,   lon:-102, tz:-6,   aliases:['mexico','mexican','mexico city','ciudad de mexico','cdmx','yucatan','oaxaca'] },
    '558': { name:'Nicaragua',   continent:'americas', culture:'latin_american', pop:7,   lat:13,   lon:-85,  tz:-6,   aliases:['nicaragua'] },
    '591': { name:'Panama',      continent:'americas', culture:'latin_american', pop:4,   lat:9,    lon:-80,  tz:-5,   aliases:['panama'] },
    '600': { name:'Paraguay',    continent:'americas', culture:'latin_american', pop:7,   lat:-23,  lon:-58,  tz:-4,   aliases:['paraguay'] },
    '604': { name:'Peru',        continent:'americas', culture:'latin_american', pop:34,  lat:-10,  lon:-76,  tz:-5,   aliases:['peru','peruvian','lima','machu picchu','andes'] },
    '222': { name:'El Salvador', continent:'americas', culture:'latin_american', pop:6,   lat:14,   lon:-89,  tz:-6,   aliases:['el salvador','salvador'] },
    '740': { name:'Suriname',    continent:'americas', culture:'latin_american', pop:1,   lat:4,    lon:-56,  tz:-3,   aliases:['suriname'] },
    '840': { name:'United States', continent:'americas', culture:'north_american', pop:335, lat:40, lon:-98,  tz:-6,   aliases:['united states','usa','us','america','american','new york','nyc','los angeles','la','california','texas','florida','chicago','boston','seattle','d.c.','washington','silicon valley','alaska','hawaii'] },
    '858': { name:'Uruguay',     continent:'americas', culture:'latin_american', pop:3,   lat:-33,  lon:-56,  tz:-3,   aliases:['uruguay','montevideo'] },
    '862': { name:'Venezuela',   continent:'americas', culture:'latin_american', pop:29,  lat:8,    lon:-66,  tz:-4,   aliases:['venezuela','caracas'] },
    '388': { name:'Jamaica',     continent:'americas', culture:'latin_american', pop:3,   lat:18,   lon:-77,  tz:-5,   aliases:['jamaica','kingston'] },

    // --- ASIA ---
    '004': { name:'Afghanistan', continent:'asia',  culture:'middle_eastern',  pop:41,   lat:33,   lon:66,   tz:4.5,  aliases:['afghanistan','afghan','kabul'] },
    '050': { name:'Bangladesh',  continent:'asia',  culture:'south_asian',    pop:172,  lat:23,   lon:90,   tz:6,    aliases:['bangladesh','dhaka'] },
    '064': { name:'Bhutan',      continent:'asia',  culture:'south_asian',    pop:1,    lat:27,   lon:90,   tz:6,    aliases:['bhutan'] },
    '104': { name:'Myanmar',     continent:'asia',  culture:'southeast_asian',pop:54,   lat:21,   lon:96,   tz:6.5,  aliases:['myanmar','burma','yangon'] },
    '116': { name:'Cambodia',    continent:'asia',  culture:'southeast_asian',pop:17,   lat:13,   lon:105,  tz:7,    aliases:['cambodia','angkor','phnom penh'] },
    '156': { name:'China',       continent:'asia',  culture:'east_asian',     pop:1412, lat:35,   lon:104,  tz:8,    aliases:['china','chinese','beijing','shanghai','hong kong','shenzhen','prc'] },
    '158': { name:'Taiwan',      continent:'asia',  culture:'east_asian',     pop:23,   lat:24,   lon:121,  tz:8,    aliases:['taiwan','taipei'] },
    '344': { name:'Hong Kong',   continent:'asia',  culture:'east_asian',     pop:7,    lat:22.3, lon:114,  tz:8,    aliases:['hong kong'] },
    '356': { name:'India',       continent:'asia',  culture:'south_asian',    pop:1428, lat:22,   lon:79,   tz:5.5,  aliases:['india','indian','mumbai','delhi','new delhi','bangalore','bengaluru','chennai','kolkata','hyderabad','himalayas','ganges'] },
    '360': { name:'Indonesia',   continent:'asia',  culture:'southeast_asian',pop:277,  lat:-2,   lon:118,  tz:7,    aliases:['indonesia','jakarta','bali','sumatra','java'] },
    '364': { name:'Iran',        continent:'asia',  culture:'middle_eastern', pop:88,   lat:32,   lon:54,   tz:3.5,  aliases:['iran','iranian','persia','persian','tehran','isfahan'] },
    '368': { name:'Iraq',        continent:'asia',  culture:'middle_eastern', pop:45,   lat:33,   lon:44,   tz:3,    aliases:['iraq','baghdad','mesopotamia','babylon'] },
    '376': { name:'Israel',      continent:'asia',  culture:'middle_eastern', pop:9,    lat:31,   lon:35,   tz:2,    aliases:['israel','israeli','jerusalem','tel aviv'] },
    '392': { name:'Japan',       continent:'asia',  culture:'east_asian',     pop:124,  lat:36,   lon:138,  tz:9,    aliases:['japan','japanese','tokyo','kyoto','osaka','mount fuji','fuji'] },
    '398': { name:'Kazakhstan',  continent:'asia',  culture:'slavic',         pop:20,   lat:48,   lon:68,   tz:5,    aliases:['kazakhstan','astana','almaty'] },
    '400': { name:'Jordan',      continent:'asia',  culture:'middle_eastern', pop:11,   lat:31,   lon:36,   tz:3,    aliases:['jordan','amman','petra'] },
    '408': { name:'North Korea', continent:'asia',  culture:'east_asian',     pop:26,   lat:40,   lon:127,  tz:9,    aliases:['north korea','pyongyang','dprk'] },
    '410': { name:'South Korea', continent:'asia',  culture:'east_asian',     pop:52,   lat:36,   lon:128,  tz:9,    aliases:['south korea','korea','korean','seoul','busan'] },
    '414': { name:'Kuwait',      continent:'asia',  culture:'middle_eastern', pop:4,    lat:29,   lon:47,   tz:3,    aliases:['kuwait'] },
    '417': { name:'Kyrgyzstan',  continent:'asia',  culture:'slavic',         pop:7,    lat:41,   lon:74,   tz:6,    aliases:['kyrgyzstan'] },
    '418': { name:'Laos',        continent:'asia',  culture:'southeast_asian',pop:7,    lat:19,   lon:102,  tz:7,    aliases:['laos','vientiane'] },
    '422': { name:'Lebanon',     continent:'asia',  culture:'middle_eastern', pop:5,    lat:34,   lon:36,   tz:2,    aliases:['lebanon','beirut'] },
    '458': { name:'Malaysia',    continent:'asia',  culture:'southeast_asian',pop:34,   lat:3,    lon:102,  tz:8,    aliases:['malaysia','kuala lumpur','borneo'] },
    '496': { name:'Mongolia',    continent:'asia',  culture:'east_asian',     pop:3,    lat:46,   lon:103,  tz:8,    aliases:['mongolia','ulaanbaatar','gobi'] },
    '524': { name:'Nepal',       continent:'asia',  culture:'south_asian',    pop:30,   lat:28,   lon:84,   tz:5.75, aliases:['nepal','kathmandu','everest'] },
    '512': { name:'Oman',        continent:'asia',  culture:'middle_eastern', pop:5,    lat:21,   lon:57,   tz:4,    aliases:['oman','muscat'] },
    '586': { name:'Pakistan',    continent:'asia',  culture:'south_asian',    pop:240,  lat:30,   lon:70,   tz:5,    aliases:['pakistan','karachi','lahore','islamabad'] },
    '608': { name:'Philippines', continent:'asia',  culture:'southeast_asian',pop:117,  lat:13,   lon:122,  tz:8,    aliases:['philippines','filipino','manila','cebu'] },
    '634': { name:'Qatar',       continent:'asia',  culture:'middle_eastern', pop:3,    lat:25,   lon:51,   tz:3,    aliases:['qatar','doha'] },
    '682': { name:'Saudi Arabia',continent:'asia',  culture:'middle_eastern', pop:36,   lat:24,   lon:45,   tz:3,    aliases:['saudi arabia','saudi','riyadh','mecca','medina'] },
    '702': { name:'Singapore',   continent:'asia',  culture:'southeast_asian',pop:6,    lat:1.3,  lon:103.8,tz:8,    aliases:['singapore'] },
    '144': { name:'Sri Lanka',   continent:'asia',  culture:'south_asian',    pop:22,   lat:7,    lon:81,   tz:5.5,  aliases:['sri lanka','colombo','ceylon'] },
    '760': { name:'Syria',       continent:'asia',  culture:'middle_eastern', pop:22,   lat:35,   lon:38,   tz:3,    aliases:['syria','damascus','aleppo'] },
    '762': { name:'Tajikistan',  continent:'asia',  culture:'slavic',         pop:10,   lat:38,   lon:71,   tz:5,    aliases:['tajikistan'] },
    '764': { name:'Thailand',    continent:'asia',  culture:'southeast_asian',pop:72,   lat:15,   lon:101,  tz:7,    aliases:['thailand','thai','bangkok','phuket'] },
    '792': { name:'Turkey',      continent:'asia',  culture:'middle_eastern', pop:85,   lat:39,   lon:35,   tz:3,    aliases:['turkey','turkish','istanbul','constantinople','ankara','anatolia'] },
    '795': { name:'Turkmenistan',continent:'asia',  culture:'slavic',         pop:6,    lat:39,   lon:59,   tz:5,    aliases:['turkmenistan'] },
    '784': { name:'UAE',         continent:'asia',  culture:'middle_eastern', pop:10,   lat:24,   lon:54,   tz:4,    aliases:['uae','united arab emirates','dubai','abu dhabi','emirates'] },
    '860': { name:'Uzbekistan',  continent:'asia',  culture:'slavic',         pop:35,   lat:41,   lon:64,   tz:5,    aliases:['uzbekistan','tashkent','samarkand'] },
    '704': { name:'Vietnam',     continent:'asia',  culture:'southeast_asian',pop:100,  lat:16,   lon:108,  tz:7,    aliases:['vietnam','vietnamese','hanoi','ho chi minh','saigon'] },
    '887': { name:'Yemen',       continent:'asia',  culture:'middle_eastern', pop:34,   lat:15,   lon:48,   tz:3,    aliases:['yemen','sanaa'] },

    // --- EUROPE ---
    '008': { name:'Albania',     continent:'europe', culture:'mediterranean',  pop:3,    lat:41,   lon:20,   tz:1,    aliases:['albania','tirana'] },
    '051': { name:'Armenia',     continent:'europe', culture:'slavic',         pop:3,    lat:40,   lon:45,   tz:4,    aliases:['armenia','yerevan'] },
    '040': { name:'Austria',     continent:'europe', culture:'western_european', pop:9,  lat:47,   lon:14,   tz:1,    aliases:['austria','vienna','wien'] },
    '112': { name:'Belarus',     continent:'europe', culture:'slavic',         pop:9,    lat:53,   lon:28,   tz:3,    aliases:['belarus','minsk'] },
    '056': { name:'Belgium',     continent:'europe', culture:'western_european', pop:12, lat:51,   lon:4,    tz:1,    aliases:['belgium','brussels','antwerp'] },
    '070': { name:'Bosnia and Herz.', continent:'europe', culture:'slavic',   pop:3,    lat:44,   lon:18,   tz:1,    aliases:['bosnia','bosnia and herzegovina','sarajevo'] },
    '100': { name:'Bulgaria',    continent:'europe', culture:'slavic',         pop:6,    lat:43,   lon:25,   tz:2,    aliases:['bulgaria','sofia'] },
    '191': { name:'Croatia',     continent:'europe', culture:'mediterranean',  pop:4,    lat:45,   lon:16,   tz:1,    aliases:['croatia','zagreb','dalmatia'] },
    '196': { name:'Cyprus',      continent:'europe', culture:'mediterranean',  pop:1,    lat:35,   lon:33,   tz:2,    aliases:['cyprus'] },
    '203': { name:'Czechia',     continent:'europe', culture:'slavic',         pop:11,   lat:50,   lon:15,   tz:1,    aliases:['czechia','czech republic','prague','bohemia'] },
    '208': { name:'Denmark',     continent:'europe', culture:'nordic',         pop:6,    lat:56,   lon:10,   tz:1,    aliases:['denmark','copenhagen','danish'] },
    '233': { name:'Estonia',     continent:'europe', culture:'nordic',         pop:1,    lat:59,   lon:26,   tz:2,    aliases:['estonia','tallinn'] },
    '246': { name:'Finland',     continent:'europe', culture:'nordic',         pop:6,    lat:64,   lon:26,   tz:2,    aliases:['finland','helsinki','finnish','lapland'] },
    '250': { name:'France',      continent:'europe', culture:'western_european', pop:65, lat:47,   lon:2,    tz:1,    aliases:['france','french','paris','provence','brittany','côte dazur','riviera','marseille','lyon'] },
    '268': { name:'Georgia',     continent:'europe', culture:'slavic',         pop:4,    lat:42,   lon:43,   tz:4,    aliases:['georgia','tbilisi','caucasus'] },
    '276': { name:'Germany',     continent:'europe', culture:'western_european', pop:84, lat:51,   lon:10,   tz:1,    aliases:['germany','german','berlin','munich','bavaria','hamburg'] },
    '300': { name:'Greece',      continent:'europe', culture:'mediterranean',  pop:10,   lat:39,   lon:22,   tz:2,    aliases:['greece','greek','athens','crete','santorini','aegean'] },
    '348': { name:'Hungary',     continent:'europe', culture:'slavic',         pop:10,   lat:47,   lon:19,   tz:1,    aliases:['hungary','budapest'] },
    '352': { name:'Iceland',     continent:'europe', culture:'nordic',         pop:1,    lat:65,   lon:-18,  tz:0,    aliases:['iceland','reykjavik'] },
    '372': { name:'Ireland',     continent:'europe', culture:'western_european', pop:5,  lat:53,   lon:-8,   tz:0,    aliases:['ireland','irish','dublin'] },
    '380': { name:'Italy',       continent:'europe', culture:'mediterranean',  pop:59,   lat:42,   lon:12,   tz:1,    aliases:['italy','italian','rome','milan','venice','florence','sicily','tuscany','naples'] },
    '428': { name:'Latvia',      continent:'europe', culture:'nordic',         pop:2,    lat:57,   lon:25,   tz:2,    aliases:['latvia','riga'] },
    '440': { name:'Lithuania',   continent:'europe', culture:'slavic',         pop:3,    lat:55,   lon:24,   tz:2,    aliases:['lithuania','vilnius'] },
    '442': { name:'Luxembourg',  continent:'europe', culture:'western_european', pop:1,  lat:49.8, lon:6.1,  tz:1,    aliases:['luxembourg'] },
    '498': { name:'Moldova',     continent:'europe', culture:'slavic',         pop:3,    lat:47,   lon:28,   tz:2,    aliases:['moldova'] },
    '499': { name:'Montenegro',  continent:'europe', culture:'slavic',         pop:1,    lat:42,   lon:19,   tz:1,    aliases:['montenegro'] },
    '528': { name:'Netherlands', continent:'europe', culture:'western_european', pop:18, lat:52,   lon:5,    tz:1,    aliases:['netherlands','holland','dutch','amsterdam','rotterdam'] },
    '807': { name:'North Macedonia', continent:'europe', culture:'slavic',    pop:2,    lat:42,   lon:22,   tz:1,    aliases:['north macedonia','macedonia','skopje'] },
    '578': { name:'Norway',      continent:'europe', culture:'nordic',         pop:5,    lat:62,   lon:10,   tz:1,    aliases:['norway','oslo','norwegian','fjord','fjords'] },
    '616': { name:'Poland',      continent:'europe', culture:'slavic',         pop:38,   lat:52,   lon:19,   tz:1,    aliases:['poland','polish','warsaw','krakow'] },
    '620': { name:'Portugal',    continent:'europe', culture:'mediterranean',  pop:10,   lat:39.5, lon:-8,   tz:0,    aliases:['portugal','portuguese','lisbon','porto'] },
    '642': { name:'Romania',     continent:'europe', culture:'slavic',         pop:19,   lat:46,   lon:25,   tz:2,    aliases:['romania','bucharest','transylvania'] },
    '643': { name:'Russia',      continent:'europe', culture:'slavic',         pop:144,  lat:61,   lon:100,  tz:3,    aliases:['russia','russian','moscow','st petersburg','siberia','kremlin'] },
    '688': { name:'Serbia',      continent:'europe', culture:'slavic',         pop:7,    lat:44,   lon:21,   tz:1,    aliases:['serbia','belgrade'] },
    '703': { name:'Slovakia',    continent:'europe', culture:'slavic',         pop:5,    lat:49,   lon:20,   tz:1,    aliases:['slovakia','bratislava'] },
    '705': { name:'Slovenia',    continent:'europe', culture:'slavic',         pop:2,    lat:46,   lon:15,   tz:1,    aliases:['slovenia','ljubljana'] },
    '724': { name:'Spain',       continent:'europe', culture:'mediterranean',  pop:48,   lat:40,   lon:-4,   tz:1,    aliases:['spain','spanish','madrid','barcelona','catalonia','andalusia','seville'] },
    '752': { name:'Sweden',      continent:'europe', culture:'nordic',         pop:10,   lat:62,   lon:15,   tz:1,    aliases:['sweden','stockholm','swedish','scandinavia'] },
    '756': { name:'Switzerland', continent:'europe', culture:'western_european', pop:9,  lat:47,   lon:8,    tz:1,    aliases:['switzerland','swiss','zurich','geneva','alps'] },
    '804': { name:'Ukraine',     continent:'europe', culture:'slavic',         pop:36,   lat:49,   lon:32,   tz:2,    aliases:['ukraine','ukrainian','kyiv','kiev','crimea'] },
    '826': { name:'United Kingdom', continent:'europe', culture:'western_european', pop:68, lat:54, lon:-2,  tz:0,    aliases:['united kingdom','uk','britain','great britain','england','scotland','wales','london','manchester','edinburgh'] },

    // --- OCEANIA ---
    '036': { name:'Australia',   continent:'oceania', culture:'oceanian',      pop:26,   lat:-26,  lon:134,  tz:10,   aliases:['australia','australian','sydney','melbourne','brisbane','perth','outback','great barrier reef'] },
    '242': { name:'Fiji',        continent:'oceania', culture:'oceanian',      pop:1,    lat:-18,  lon:178,  tz:12,   aliases:['fiji'] },
    '554': { name:'New Zealand', continent:'oceania', culture:'oceanian',      pop:5,    lat:-41,  lon:174,  tz:12,   aliases:['new zealand','nz','auckland','wellington','maori','aotearoa'] },
    '598': { name:'Papua New Guinea', continent:'oceania', culture:'oceanian', pop:10,   lat:-6,   lon:145,  tz:10,   aliases:['papua new guinea','png'] },
    '540': { name:'New Caledonia', continent:'oceania', culture:'oceanian',    pop:0.3,  lat:-21,  lon:166,  tz:11,   aliases:['new caledonia'] },
    '548': { name:'Vanuatu',     continent:'oceania', culture:'oceanian',      pop:0.3,  lat:-17,  lon:168,  tz:11,   aliases:['vanuatu'] },
    '090': { name:'Solomon Islands', continent:'oceania', culture:'oceanian',  pop:0.7,  lat:-9,   lon:159,  tz:11,   aliases:['solomon islands'] },
};

const CONTINENTS = {
    africa:   { name:'Africa',        lat:0,   lon:20,   label:'across Africa' },
    americas: { name:'Americas',      lat:0,   lon:-75,  label:'across the Americas' },
    asia:     { name:'Asia',          lat:35,  lon:95,   label:'across Asia' },
    europe:   { name:'Europe',        lat:55,  lon:10,   label:'across Europe' },
    oceania:  { name:'Oceania',       lat:-25, lon:140,  label:'across Oceania' },
};

/* regions = named clusters for prompt parsing */
const REGIONS = {
    'middle east':       { countries:['364','368','376','400','414','422','512','634','682','760','784','887'] },
    'europe':            { countries:Object.keys(COUNTRIES).filter(id => COUNTRIES[id].continent==='europe') },
    'africa':            { countries:Object.keys(COUNTRIES).filter(id => COUNTRIES[id].continent==='africa') },
    'asia':              { countries:Object.keys(COUNTRIES).filter(id => COUNTRIES[id].continent==='asia') },
    'americas':          { countries:Object.keys(COUNTRIES).filter(id => COUNTRIES[id].continent==='americas') },
    'north america':     { countries:['124','840','484'] },
    'south america':     { countries:['032','068','076','152','170','218','600','604','740','858','862'] },
    'central america':   { countries:['188','222','320','340','484','558','591'] },
    'oceania':           { countries:Object.keys(COUNTRIES).filter(id => COUNTRIES[id].continent==='oceania') },
    'scandinavia':       { countries:['208','246','352','578','752'] },
    'baltics':           { countries:['233','428','440'] },
    'balkans':           { countries:['008','070','191','300','499','688','807','705'] },
    'mediterranean':     { countries:['008','196','250','300','380','422','504','620','724','760','788','792'] },
    'caribbean':         { countries:['192','214','332','388'] },
    'east asia':         { countries:['156','158','344','392','408','410','496'] },
    'south asia':        { countries:['050','064','144','356','524','586'] },
    'southeast asia':    { countries:['104','116','360','418','458','608','702','764','704'] },
    'central asia':      { countries:['398','417','762','795','860'] },
    'gulf':              { countries:['414','512','634','682','784','887'] },
    'sahara':            { countries:['012','148','434','466','478','504','562','729','788'] },
    'sub-saharan africa':{ countries:Object.keys(COUNTRIES).filter(id => COUNTRIES[id].continent==='africa' && COUNTRIES[id].lat < 20) },
    'horn of africa':    { countries:['231','232','262','706'] },
};

const ALL_COUNTRY_IDS = Object.keys(COUNTRIES);
