/* =========================================================
   countries.js — country metadata keyed by ISO 3166-1
   numeric code (matches the world-atlas TopoJSON IDs).
   Population in millions (approx, for simulation purposes).
   ========================================================= */

const COUNTRIES = {
    // --- AFRICA ---
    '012': { name:'Algeria',     continent:'africa', culture:'middle_eastern',  pop:45,   lat:28,   lon:2,    tz:1,    aliases:['algeria','algerian'] },
    '024': { name:'Angola',      continent:'africa', culture:'african_west',    pop:34,   lat:-12,  lon:18,   tz:1,    aliases:['angola'] },
    '072': { name:'Botswana',    continent:'africa', culture:'african_south',   pop:2,    lat:-22,  lon:24,   tz:2,    aliases:['botswana'] },
    '854': { name:'Burkina Faso',continent:'africa', culture:'african_west',    pop:22,   lat:12,   lon:-1,   tz:0,    aliases:['burkina','burkina faso'] },
    '108': { name:'Burundi',     continent:'africa', culture:'african_east',    pop:13,   lat:-3,   lon:30,   tz:2,    aliases:['burundi'] },
    '120': { name:'Cameroon',    continent:'africa', culture:'african_west',    pop:27,   lat:6,    lon:12,   tz:1,    aliases:['cameroon'] },
    '140': { name:'Central African Republic', continent:'africa', culture:'african_west', pop:5, lat:6, lon:21, tz:1, aliases:['car','central african republic','central africa'] },
    '148': { name:'Chad',        continent:'africa', culture:'african_west',    pop:17,   lat:15,   lon:19,   tz:1,    aliases:['chad'] },
    '180': { name:'DR Congo',    continent:'africa', culture:'african_west',    pop:99,   lat:-2,   lon:23,   tz:1,    aliases:['congo','dr congo','drc','democratic republic of congo'] },
    '178': { name:'Congo',       continent:'africa', culture:'african_west',    pop:5,    lat:-1,   lon:15,   tz:1,    aliases:['republic of congo','congo-brazzaville'] },
    '384': { name:'Ivory Coast', continent:'africa', culture:'african_west',    pop:28,   lat:8,    lon:-5,   tz:0,    aliases:['ivory coast',"côte d'ivoire",'cote divoire','cote d ivoire'] },
    '262': { name:'Djibouti',    continent:'africa', culture:'african_east',    pop:1,    lat:12,   lon:43,   tz:3,    aliases:['djibouti'] },
    '818': { name:'Egypt',       continent:'africa', culture:'middle_eastern',  pop:110,  lat:27,   lon:30,   tz:2,    aliases:['egypt','egyptian','cairo','nile'] },
    '231': { name:'Ethiopia',    continent:'africa', culture:'african_east',    pop:126,  lat:9,    lon:40,   tz:3,    aliases:['ethiopia','ethiopian','addis'] },
    '232': { name:'Eritrea',     continent:'africa', culture:'african_east',    pop:4,    lat:15,   lon:39,   tz:3,    aliases:['eritrea'] },
    '266': { name:'Gabon',       continent:'africa', culture:'african_west',    pop:2,    lat:-1,   lon:11,   tz:1,    aliases:['gabon'] },
    '288': { name:'Ghana',       continent:'africa', culture:'african_west',    pop:34,   lat:8,    lon:-1,   tz:0,    aliases:['ghana','ghanaian'] },
    '324': { name:'Guinea',      continent:'africa', culture:'african_west',    pop:14,   lat:10,   lon:-10,  tz:0,    aliases:['guinea'] },
    '404': { name:'Kenya',       continent:'africa', culture:'african_east',    pop:55,   lat:1,    lon:38,   tz:3,    aliases:['kenya','kenyan','nairobi'] },
    '426': { name:'Lesotho',     continent:'africa', culture:'african_south',   pop:2,    lat:-29,  lon:28,   tz:2,    aliases:['lesotho'] },
    '430': { name:'Liberia',     continent:'africa', culture:'african_west',    pop:5,    lat:6,    lon:-9,   tz:0,    aliases:['liberia'] },
    '434': { name:'Libya',       continent:'africa', culture:'middle_eastern',  pop:7,    lat:27,   lon:17,   tz:2,    aliases:['libya'] },
    '450': { name:'Madagascar',  continent:'africa', culture:'african_east',    pop:30,   lat:-19,  lon:47,   tz:3,    aliases:['madagascar'] },
    '454': { name:'Malawi',      continent:'africa', culture:'african_east',    pop:21,   lat:-13,  lon:34,   tz:2,    aliases:['malawi'] },
    '466': { name:'Mali',        continent:'africa', culture:'african_west',    pop:22,   lat:17,   lon:-4,   tz:0,    aliases:['mali'] },
    '478': { name:'Mauritania',  continent:'africa', culture:'middle_eastern',  pop:5,    lat:20,   lon:-10,  tz:0,    aliases:['mauritania'] },
    '504': { name:'Morocco',     continent:'africa', culture:'middle_eastern',  pop:38,   lat:32,   lon:-6,   tz:1,    aliases:['morocco','moroccan','marrakech','casablanca'] },
    '508': { name:'Mozambique',  continent:'africa', culture:'african_east',    pop:33,   lat:-18,  lon:35,   tz:2,    aliases:['mozambique'] },
    '516': { name:'Namibia',     continent:'africa', culture:'african_south',   pop:3,    lat:-22,  lon:17,   tz:2,    aliases:['namibia'] },
    '562': { name:'Niger',       continent:'africa', culture:'african_west',    pop:26,   lat:17,   lon:8,    tz:1,    aliases:['niger'] },
    '566': { name:'Nigeria',     continent:'africa', culture:'african_west',    pop:223,  lat:10,   lon:8,    tz:1,    aliases:['nigeria','nigerian','lagos','abuja'] },
    '646': { name:'Rwanda',      continent:'africa', culture:'african_east',    pop:14,   lat:-2,   lon:30,   tz:2,    aliases:['rwanda'] },
    '686': { name:'Senegal',     continent:'africa', culture:'african_west',    pop:17,   lat:14,   lon:-15,  tz:0,    aliases:['senegal','dakar'] },
    '694': { name:'Sierra Leone',continent:'africa', culture:'african_west',    pop:8,    lat:8,    lon:-12,  tz:0,    aliases:['sierra leone'] },
    '706': { name:'Somalia',     continent:'africa', culture:'african_east',    pop:17,   lat:6,    lon:46,   tz:3,    aliases:['somalia'] },
    '710': { name:'South Africa',continent:'africa', culture:'african_south',   pop:61,   lat:-29,  lon:24,   tz:2,    aliases:['south africa','south african','cape town','johannesburg','jozi'] },
    '728': { name:'South Sudan', continent:'africa', culture:'african_east',    pop:11,   lat:7,    lon:31,   tz:3,    aliases:['south sudan'] },
    '729': { name:'Sudan',       continent:'africa', culture:'middle_eastern',  pop:48,   lat:15,   lon:30,   tz:2,    aliases:['sudan','sudanese','khartoum'] },
    '834': { name:'Tanzania',    continent:'africa', culture:'african_east',    pop:66,   lat:-6,   lon:35,   tz:3,    aliases:['tanzania','tanzanian','zanzibar','kilimanjaro'] },
    '768': { name:'Togo',        continent:'africa', culture:'african_west',    pop:9,    lat:8,    lon:1,    tz:0,    aliases:['togo'] },
    '788': { name:'Tunisia',     continent:'africa', culture:'middle_eastern',  pop:12,   lat:34,   lon:9,    tz:1,    aliases:['tunisia'] },
    '800': { name:'Uganda',      continent:'africa', culture:'african_east',    pop:48,   lat:1,    lon:32,   tz:3,    aliases:['uganda','ugandan'] },
    '894': { name:'Zambia',      continent:'africa', culture:'african_south',   pop:20,   lat:-13,  lon:28,   tz:2,    aliases:['zambia'] },
    '716': { name:'Zimbabwe',    continent:'africa', culture:'african_south',   pop:16,   lat:-19,  lon:30,   tz:2,    aliases:['zimbabwe'] },

    // --- AMERICAS ---
    '032': { name:'Argentina',   continent:'americas', culture:'latin_american', pop:46,  lat:-35,  lon:-65,  tz:-3,   aliases:['argentina','argentinian','buenos aires','patagonia'] },
    '068': { name:'Bolivia',     continent:'americas', culture:'latin_american', pop:12,  lat:-17,  lon:-65,  tz:-4,   aliases:['bolivia','la paz'] },
    '076': { name:'Brazil',      continent:'americas', culture:'latin_american', pop:216, lat:-10,  lon:-55,  tz:-3,   aliases:['brazil','brasil','brazilian','rio','rio de janeiro','sao paulo','são paulo','amazon'] },
    '124': { name:'Canada',      continent:'americas', culture:'north_american', pop:39,  lat:57,   lon:-106, tz:-5,   aliases:['canada','canadian','toronto','vancouver','quebec','ontario'] },
    '152': { name:'Chile',       continent:'americas', culture:'latin_american', pop:20,  lat:-33,  lon:-71,  tz:-4,   aliases:['chile','chilean','santiago','patagonia'] },
    '170': { name:'Colombia',    continent:'americas', culture:'latin_american', pop:52,  lat:4,    lon:-74,  tz:-5,   aliases:['colombia','colombian','bogota','bogotá','medellin'] },
    '188': { name:'Costa Rica',  continent:'americas', culture:'latin_american', pop:5,   lat:10,   lon:-84,  tz:-6,   aliases:['costa rica'] },
    '192': { name:'Cuba',        continent:'americas', culture:'latin_american', pop:11,  lat:22,   lon:-78,  tz:-5,   aliases:['cuba','cuban','havana'] },
    '214': { name:'Dominican Republic', continent:'americas', culture:'latin_american', pop:11, lat:19, lon:-70, tz:-4, aliases:['dominican republic','dominican'] },
    '218': { name:'Ecuador',     continent:'americas', culture:'latin_american', pop:18,  lat:-1,   lon:-78,  tz:-5,   aliases:['ecuador','galapagos'] },
    '320': { name:'Guatemala',   continent:'americas', culture:'latin_american', pop:18,  lat:15,   lon:-90,  tz:-6,   aliases:['guatemala'] },
    '332': { name:'Haiti',       continent:'americas', culture:'latin_american', pop:12,  lat:19,   lon:-72,  tz:-5,   aliases:['haiti','haitian','port-au-prince'] },
    '340': { name:'Honduras',    continent:'americas', culture:'latin_american', pop:11,  lat:15,   lon:-86,  tz:-6,   aliases:['honduras'] },
    '484': { name:'Mexico',      continent:'americas', culture:'latin_american', pop:128, lat:23,   lon:-102, tz:-6,   aliases:['mexico','mexican','mexico city','ciudad de mexico','cdmx','yucatan','oaxaca'] },
    '558': { name:'Nicaragua',   continent:'americas', culture:'latin_american', pop:7,   lat:13,   lon:-85,  tz:-6,   aliases:['nicaragua'] },
    '591': { name:'Panama',      continent:'americas', culture:'latin_american', pop:4,   lat:9,    lon:-80,  tz:-5,   aliases:['panama'] },
    '600': { name:'Paraguay',    continent:'americas', culture:'latin_american', pop:7,   lat:-23,  lon:-58,  tz:-4,   aliases:['paraguay'] },
    '604': { name:'Peru',        continent:'americas', culture:'latin_american', pop:34,  lat:-10,  lon:-76,  tz:-5,   aliases:['peru','peruvian','lima','machu picchu','andes'] },
    '222': { name:'El Salvador', continent:'americas', culture:'latin_american', pop:6,   lat:14,   lon:-89,  tz:-6,   aliases:['el salvador','salvador'] },
    '740': { name:'Suriname',    continent:'americas', culture:'latin_american', pop:1,   lat:4,    lon:-56,  tz:-3,   aliases:['suriname'] },
    '840': { name:'United States', continent:'americas', culture:'north_american', pop:335, lat:40, lon:-98,  tz:-6,   aliases:['united states','usa','us','america','american','new york','nyc','los angeles','la','california','texas','florida','chicago','boston','seattle','d.c.','washington','silicon valley','alaska','hawaii'] },
    '858': { name:'Uruguay',     continent:'americas', culture:'latin_american', pop:3,   lat:-33,  lon:-56,  tz:-3,   aliases:['uruguay','montevideo'] },
    '862': { name:'Venezuela',   continent:'americas', culture:'latin_american', pop:29,  lat:8,    lon:-66,  tz:-4,   aliases:['venezuela','caracas'] },
    '388': { name:'Jamaica',     continent:'americas', culture:'latin_american', pop:3,   lat:18,   lon:-77,  tz:-5,   aliases:['jamaica','kingston'] },

    // --- ASIA ---
    '004': { name:'Afghanistan', continent:'asia',  culture:'middle_eastern',  pop:41,   lat:33,   lon:66,   tz:4.5,  aliases:['afghanistan','afghan','kabul'] },
    '050': { name:'Bangladesh',  continent:'asia',  culture:'south_asian',    pop:172,  lat:23,   lon:90,   tz:6,    aliases:['bangladesh','dhaka'] },
    '064': { name:'Bhutan',      continent:'asia',  culture:'south_asian',    pop:1,    lat:27,   lon:90,   tz:6,    aliases:['bhutan'] },
    '104': { name:'Myanmar',     continent:'asia',  culture:'southeast_asian',pop:54,   lat:21,   lon:96,   tz:6.5,  aliases:['myanmar','burma','yangon'] },
    '116': { name:'Cambodia',    continent:'asia',  culture:'southeast_asian',pop:17,   lat:13,   lon:105,  tz:7,    aliases:['cambodia','angkor','phnom penh'] },
    '156': { name:'China',       continent:'asia',  culture:'east_asian',     pop:1412, lat:35,   lon:104,  tz:8,    aliases:['china','chinese','beijing','shanghai','hong kong','shenzhen','prc'] },
    '158': { name:'Taiwan',      continent:'asia',  culture:'east_asian',     pop:23,   lat:24,   lon:121,  tz:8,    aliases:['taiwan','taipei'] },
    '344': { name:'Hong Kong',   continent:'asia',  culture:'east_asian',     pop:7,    lat:22.3, lon:114,  tz:8,    aliases:['hong kong'] },
    '356': { name:'India',       continent:'asia',  culture:'south_asian',    pop:1428, lat:22,   lon:79,   tz:5.5,  aliases:['india','indian','mumbai','delhi','new delhi','bangalore','bengaluru','chennai','kolkata','hyderabad','himalayas','ganges'] },
    '360': { name:'Indonesia',   continent:'asia',  culture:'southeast_asian',pop:277,  lat:-2,   lon:118,  tz:7,    aliases:['indonesia','jakarta','bali','sumatra','java'] },
    '364': { name:'Iran',        continent:'asia',  culture:'middle_eastern', pop:88,   lat:32,   lon:54,   tz:3.5,  aliases:['iran','iranian','persia','persian','tehran','isfahan'] },
    '368': { name:'Iraq',        continent:'asia',  culture:'middle_eastern', pop:45,   lat:33,   lon:44,   tz:3,    aliases:['iraq','baghdad','mesopotamia','babylon'] },
    '376': { name:'Israel',      continent:'asia',  culture:'middle_eastern', pop:9,    lat:31,   lon:35,   tz:2,    aliases:['israel','israeli','jerusalem','tel aviv'] },
    '392': { name:'Japan',       continent:'asia',  culture:'east_asian',     pop:124,  lat:36,   lon:138,  tz:9,    aliases:['japan','japanese','tokyo','kyoto','osaka','mount fuji','fuji'] },
    '398': { name:'Kazakhstan',  continent:'asia',  culture:'slavic',         pop:20,   lat:48,   lon:68,   tz:5,    aliases:['kazakhstan','astana','almaty'] },
    '400': { name:'Jordan',      continent:'asia',  culture:'middle_eastern', pop:11,   lat:31,   lon:36,   tz:3,    aliases:['jordan','amman','petra'] },
    '408': { name:'North Korea', continent:'asia',  culture:'east_asian',     pop:26,   lat:40,   lon:127,  tz:9,    aliases:['north korea','pyongyang','dprk'] },
    '410': { name:'South Korea', continent:'asia',  culture:'east_asian',     pop:52,   lat:36,   lon:128,  tz:9,    aliases:['south korea','korea','korean','seoul','busan'] },
    '414': { name:'Kuwait',      continent:'asia',  culture:'middle_eastern', pop:4,    lat:29,   lon:47,   tz:3,    aliases:['kuwait'] },
    '417': { name:'Kyrgyzstan',  continent:'asia',  culture:'slavic',         pop:7,    lat:41,   lon:74,   tz:6,    aliases:['kyrgyzstan'] },
    '418': { name:'Laos',        continent:'asia',  culture:'southeast_asian',pop:7,    lat:19,   lon:102,  tz:7,    aliases:['laos','vientiane'] },
    '422': { name:'Lebanon',     continent:'asia',  culture:'middle_eastern', pop:5,    lat:34,   lon:36,   tz:2,    aliases:['lebanon','beirut'] },
    '458': { name:'Malaysia',    continent:'asia',  culture:'southeast_asian',pop:34,   lat:3,    lon:102,  tz:8,    aliases:['malaysia','kuala lumpur','borneo'] },
    '496': { name:'Mongolia',    continent:'asia',  culture:'east_asian',     pop:3,    lat:46,   lon:103,  tz:8,    aliases:['mongolia','ulaanbaatar','gobi'] },
    '524': { name:'Nepal',       continent:'asia',  culture:'south_asian',    pop:30,   lat:28,   lon:84,   tz:5.75, aliases:['nepal','kathmandu','everest'] },
    '512': { name:'Oman',        continent:'asia',  culture:'middle_eastern', pop:5,    lat:21,   lon:57,   tz:4,    aliases:['oman','muscat'] },
    '586': { name:'Pakistan',    continent:'asia',  culture:'south_asian',    pop:240,  lat:30,   lon:70,   tz:5,    aliases:['pakistan','karachi','lahore','islamabad'] },
    '608': { name:'Philippines', continent:'asia',  culture:'southeast_asian',pop:117,  lat:13,   lon:122,  tz:8,    aliases:['philippines','filipino','manila','cebu'] },
    '634': { name:'Qatar',       continent:'asia',  culture:'middle_eastern', pop:3,    lat:25,   lon:51,   tz:3,    aliases:['qatar','doha'] },
    '682': { name:'Saudi Arabia',continent:'asia',  culture:'middle_eastern', pop:36,   lat:24,   lon:45,   tz:3,    aliases:['saudi arabia','saudi','riyadh','mecca','medina'] },
    '702': { name:'Singapore',   continent:'asia',  culture:'southeast_asian',pop:6,    lat:1.3,  lon:103.8,tz:8,    aliases:['singapore'] },
    '144': { name:'Sri Lanka',   continent:'asia',  culture:'south_asian',    pop:22,   lat:7,    lon:81,   tz:5.5,  aliases:['sri lanka','colombo','ceylon'] },
    '760': { name:'Syria',       continent:'asia',  culture:'middle_eastern', pop:22,   lat:35,   lon:38,   tz:3,    aliases:['syria','damascus','aleppo'] },
    '762': { name:'Tajikistan',  continent:'asia',  culture:'slavic',         pop:10,   lat:38,   lon:71,   tz:5,    aliases:['tajikistan'] },
    '764': { name:'Thailand',    continent:'asia',  culture:'southeast_asian',pop:72,   lat:15,   lon:101,  tz:7,    aliases:['thailand','thai','bangkok','phuket'] },
    '792': { name:'Turkey',      continent:'asia',  culture:'middle_eastern', pop:85,   lat:39,   lon:35,   tz:3,    aliases:['turkey','turkish','istanbul','constantinople','ankara','anatolia'] },
    '795': { name:'Turkmenistan',continent:'asia',  culture:'slavic',         pop:6,    lat:39,   lon:59,   tz:5,    aliases:['turkmenistan'] },
    '784': { name:'UAE',         continent:'asia',  culture:'middle_eastern', pop:10,   lat:24,   lon:54,   tz:4,    aliases:['uae','united arab emirates','dubai','abu dhabi','emirates'] },
    '860': { name:'Uzbekistan',  continent:'asia',  culture:'slavic',         pop:35,   lat:41,   lon:64,   tz:5,    aliases:['uzbekistan','tashkent','samarkand'] },
    '704': { name:'Vietnam',     continent:'asia',  culture:'southeast_asian',pop:100,  lat:16,   lon:108,  tz:7,    aliases:['vietnam','vietnamese','hanoi','ho chi minh','saigon'] },
    '887': { name:'Yemen',       continent:'asia',  culture:'middle_eastern', pop:34,   lat:15,   lon:48,   tz:3,    aliases:['yemen','sanaa'] },

    // --- EUROPE ---
    '008': { name:'Albania',     continent:'europe', culture:'mediterranean',  pop:3,    lat:41,   lon:20,   tz:1,    aliases:['albania','tirana'] },
    '051': { name:'Armenia',     continent:'europe', culture:'slavic',         pop:3,    lat:40,   lon:45,   tz:4,    aliases:['armenia','yerevan'] },
    '040': { name:'Austria',     continent:'europe', culture:'western_european', pop:9,  lat:47,   lon:14,   tz:1,    aliases:['austria','vienna','wien'] },
    '112': { name:'Belarus',     continent:'europe', culture:'slavic',         pop:9,    lat:53,   lon:28,   tz:3,    aliases:['belarus','minsk'] },
    '056': { name:'Belgium',     continent:'europe', culture:'western_european', pop:12, lat:51,   lon:4,    tz:1,    aliases:['belgium','brussels','antwerp'] },
    '070': { name:'Bosnia and Herz.', continent:'europe', culture:'slavic',   pop:3,    lat:44,   lon:18,   tz:1,    aliases:['bosnia','bosnia and herzegovina','sarajevo'] },
    '100': { name:'Bulgaria',    continent:'europe', culture:'slavic',         pop:6,    lat:43,   lon:25,   tz:2,    aliases:['bulgaria','sofia'] },
    '191': { name:'Croatia',     continent:'europe', culture:'mediterranean',  pop:4,    lat:45,   lon:16,   tz:1,    aliases:['croatia','zagreb','dalmatia'] },
    '196': { name:'Cyprus',      continent:'europe', culture:'mediterranean',  pop:1,    lat:35,   lon:33,   tz:2,    aliases:['cyprus'] },
    '203': { name:'Czechia',     continent:'europe', culture:'slavic',         pop:11,   lat:50,   lon:15,   tz:1,    aliases:['czechia','czech republic','prague','bohemia'] },
    '208': { name:'Denmark',     continent:'europe', culture:'nordic',         pop:6,    lat:56,   lon:10,   tz:1,    aliases:['denmark','copenhagen','danish'] },
    '233': { name:'Estonia',     continent:'europe', culture:'nordic',         pop:1,    lat:59,   lon:26,   tz:2,    aliases:['estonia','tallinn'] },
    '246': { name:'Finland',     continent:'europe', culture:'nordic',         pop:6,    lat:64,   lon:26,   tz:2,    aliases:['finland','helsinki','finnish','lapland'] },
    '250': { name:'France',      continent:'europe', culture:'western_european', pop:65, lat:47,   lon:2,    tz:1,    aliases:['france','french','paris','provence','brittany','côte dazur','riviera','marseille','lyon'] },
    '268': { name:'Georgia',     continent:'europe', culture:'slavic',         pop:4,    lat:42,   lon:43,   tz:4,    aliases:['georgia','tbilisi','caucasus'] },
    '276': { name:'Germany',     continent:'europe', culture:'western_european', pop:84, lat:51,   lon:10,   tz:1,    aliases:['germany','german','berlin','munich','bavaria','hamburg'] },
    '300': { name:'Greece',      continent:'europe', culture:'mediterranean',  pop:10,   lat:39,   lon:22,   tz:2,    aliases:['greece','greek','athens','crete','santorini','aegean'] },
    '348': { name:'Hungary',     continent:'europe', culture:'slavic',         pop:10,   lat:47,   lon:19,   tz:1,    aliases:['hungary','budapest'] },
    '352': { name:'Iceland',     continent:'europe', culture:'nordic',         pop:1,    lat:65,   lon:-18,  tz:0,    aliases:['iceland','reykjavik'] },
    '372': { name:'Ireland',     continent:'europe', culture:'western_european', pop:5,  lat:53,   lon:-8,   tz:0,    aliases:['ireland','irish','dublin'] },
    '380': { name:'Italy',       continent:'europe', culture:'mediterranean',  pop:59,   lat:42,   lon:12,   tz:1,    aliases:['italy','italian','rome','milan','venice','florence','sicily','tuscany','naples'] },
    '428': { name:'Latvia',      continent:'europe', culture:'nordic',         pop:2,    lat:57,   lon:25,   tz:2,    aliases:['latvia','riga'] },
    '440': { name:'Lithuania',   continent:'europe', culture:'slavic',         pop:3,    lat:55,   lon:24,   tz:2,    aliases:['lithuania','vilnius'] },
    '442': { name:'Luxembourg',  continent:'europe', culture:'western_european', pop:1,  lat:49.8, lon:6.1,  tz:1,    aliases:['luxembourg'] },
    '498': { name:'Moldova',     continent:'europe', culture:'slavic',         pop:3,    lat:47,   lon:28,   tz:2,    aliases:['moldova'] },
    '499': { name:'Montenegro',  continent:'europe', culture:'slavic',         pop:1,    lat:42,   lon:19,   tz:1,    aliases:['montenegro'] },
    '528': { name:'Netherlands', continent:'europe', culture:'western_european', pop:18, lat:52,   lon:5,    tz:1,    aliases:['netherlands','holland','dutch','amsterdam','rotterdam'] },
    '807': { name:'North Macedonia', continent:'europe', culture:'slavic',    pop:2,    lat:42,   lon:22,   tz:1,    aliases:['north macedonia','macedonia','skopje'] },
    '578': { name:'Norway',      continent:'europe', culture:'nordic',         pop:5,    lat:62,   lon:10,   tz:1,    aliases:['norway','oslo','norwegian','fjord','fjords'] },
    '616': { name:'Poland',      continent:'europe', culture:'slavic',         pop:38,   lat:52,   lon:19,   tz:1,    aliases:['poland','polish','warsaw','krakow'] },
    '620': { name:'Portugal',    continent:'europe', culture:'mediterranean',  pop:10,   lat:39.5, lon:-8,   tz:0,    aliases:['portugal','portuguese','lisbon','porto'] },
    '642': { name:'Romania',     continent:'europe', culture:'slavic',         pop:19,   lat:46,   lon:25,   tz:2,    aliases:['romania','bucharest','transylvania'] },
    '643': { name:'Russia',      continent:'europe', culture:'slavic',         pop:144,  lat:61,   lon:100,  tz:3,    aliases:['russia','russian','moscow','st petersburg','siberia','kremlin'] },
    '688': { name:'Serbia',      continent:'europe', culture:'slavic',         pop:7,    lat:44,   lon:21,   tz:1,    aliases:['serbia','belgrade'] },
    '703': { name:'Slovakia',    continent:'europe', culture:'slavic',         pop:5,    lat:49,   lon:20,   tz:1,    aliases:['slovakia','bratislava'] },
    '705': { name:'Slovenia',    continent:'europe', culture:'slavic',         pop:2,    lat:46,   lon:15,   tz:1,    aliases:['slovenia','ljubljana'] },
    '724': { name:'Spain',       continent:'europe', culture:'mediterranean',  pop:48,   lat:40,   lon:-4,   tz:1,    aliases:['spain','spanish','madrid','barcelona','catalonia','andalusia','seville'] },
    '752': { name:'Sweden',      continent:'europe', culture:'nordic',         pop:10,   lat:62,   lon:15,   tz:1,    aliases:['sweden','stockholm','swedish','scandinavia'] },
    '756': { name:'Switzerland', continent:'europe', culture:'western_european', pop:9,  lat:47,   lon:8,    tz:1,    aliases:['switzerland','swiss','zurich','geneva','alps'] },
    '804': { name:'Ukraine',     continent:'europe', culture:'slavic',         pop:36,   lat:49,   lon:32,   tz:2,    aliases:['ukraine','ukrainian','kyiv','kiev','crimea'] },
    '826': { name:'United Kingdom', continent:'europe', culture:'western_european', pop:68, lat:54, lon:-2,  tz:0,    aliases:['united kingdom','uk','britain','great britain','england','scotland','wales','london','manchester','edinburgh'] },

    // --- OCEANIA ---
    '036': { name:'Australia',   continent:'oceania', culture:'oceanian',      pop:26,   lat:-26,  lon:134,  tz:10,   aliases:['australia','australian','sydney','melbourne','brisbane','perth','outback','great barrier reef'] },
    '242': { name:'Fiji',        continent:'oceania', culture:'oceanian',      pop:1,    lat:-18,  lon:178,  tz:12,   aliases:['fiji'] },
    '554': { name:'New Zealand', continent:'oceania', culture:'oceanian',      pop:5,    lat:-41,  lon:174,  tz:12,   aliases:['new zealand','nz','auckland','wellington','maori','aotearoa'] },
    '598': { name:'Papua New Guinea', continent:'oceania', culture:'oceanian', pop:10,   lat:-6,   lon:145,  tz:10,   aliases:['papua new guinea','png'] },
    '540': { name:'New Caledonia', continent:'oceania', culture:'oceanian',    pop:0.3,  lat:-21,  lon:166,  tz:11,   aliases:['new caledonia'] },
    '548': { name:'Vanuatu',     continent:'oceania', culture:'oceanian',      pop:0.3,  lat:-17,  lon:168,  tz:11,   aliases:['vanuatu'] },
    '090': { name:'Solomon Islands', continent:'oceania', culture:'oceanian',  pop:0.7,  lat:-9,   lon:159,  tz:11,   aliases:['solomon islands'] },
};

const CONTINENTS = {
    africa:   { name:'Africa',        lat:0,   lon:20,   label:'across Africa' },
    americas: { name:'Americas',      lat:0,   lon:-75,  label:'across the Americas' },
    asia:     { name:'Asia',          lat:35,  lon:95,   label:'across Asia' },
    europe:   { name:'Europe',        lat:55,  lon:10,   label:'across Europe' },
    oceania:  { name:'Oceania',       lat:-25, lon:140,  label:'across Oceania' },
};

/* regions = named clusters for prompt parsing */
const REGIONS = {
    'middle east':       { countries:['364','368','376','400','414','422','512','634','682','760','784','887'] },
    'europe':            { countries:Object.keys(COUNTRIES).filter(id => COUNTRIES[id].continent==='europe') },
    'africa':            { countries:Object.keys(COUNTRIES).filter(id => COUNTRIES[id].continent==='africa') },
    'asia':              { countries:Object.keys(COUNTRIES).filter(id => COUNTRIES[id].continent==='asia') },
    'americas':          { countries:Object.keys(COUNTRIES).filter(id => COUNTRIES[id].continent==='americas') },
    'north america':     { countries:['124','840','484'] },
    'south america':     { countries:['032','068','076','152','170','218','600','604','740','858','862'] },
    'central america':   { countries:['188','222','320','340','484','558','591'] },
    'oceania':           { countries:Object.keys(COUNTRIES).filter(id => COUNTRIES[id].continent==='oceania') },
    'scandinavia':       { countries:['208','246','352','578','752'] },
    'baltics':           { countries:['233','428','440'] },
    'balkans':           { countries:['008','070','191','300','499','688','807','705'] },
    'mediterranean':     { countries:['008','196','250','300','380','422','504','620','724','760','788','792'] },
    'caribbean':         { countries:['192','214','332','388'] },
    'east asia':         { countries:['156','158','344','392','408','410','496'] },
    'south asia':        { countries:['050','064','144','356','524','586'] },
    'southeast asia':    { countries:['104','116','360','418','458','608','702','764','704'] },
    'central asia':      { countries:['398','417','762','795','860'] },
    'gulf':              { countries:['414','512','634','682','784','887'] },
    'sahara':            { countries:['012','148','434','466','478','504','562','729','788'] },
    'sub-saharan africa':{ countries:Object.keys(COUNTRIES).filter(id => COUNTRIES[id].continent==='africa' && COUNTRIES[id].lat < 20) },
    'horn of africa':    { countries:['231','232','262','706'] },
    'west africa':       { countries:['854','120','384','288','324','430','466','478','562','566','686','694','768'] },
    'east africa':       { countries:['108','231','232','262','404','450','454','508','646','706','800','834','716','894'] },
    'southern africa':   { countries:['024','072','426','516','710','716','894'] },
    'north africa':      { countries:['012','818','434','504','729','788'] },
    'eastern europe':    { countries:['100','112','203','348','498','616','642','643','703','804'] },
    'western europe':    { countries:['040','056','250','276','372','442','528','826','756'] },
    'northern europe':   { countries:['208','233','246','352','428','440','578','752'] },
    'andes':             { countries:['032','068','152','170','218','604'] },
    'amazon':            { countries:['076','218','604','862'] },
    'himalayas':         { countries:['156','356','524','586','064'] },
    'iberia':            { countries:['620','724'] },
    'british isles':     { countries:['826','372'] },
};

const ALL_COUNTRY_IDS = Object.keys(COUNTRIES);

/* ISO 3166-1 numeric → alpha-2 so we can build flag emojis as regional indicators. */
const ISO_NUM_TO_A2 = {
    '004':'AF','008':'AL','012':'DZ','024':'AO','032':'AR','036':'AU','040':'AT','050':'BD','051':'AM','056':'BE',
    '064':'BT','068':'BO','070':'BA','072':'BW','076':'BR','090':'SB','100':'BG','104':'MM','108':'BI','112':'BY',
    '116':'KH','120':'CM','124':'CA','140':'CF','144':'LK','148':'TD','152':'CL','156':'CN','158':'TW','170':'CO',
    '178':'CG','180':'CD','188':'CR','191':'HR','192':'CU','196':'CY','203':'CZ','208':'DK','214':'DO','218':'EC',
    '222':'SV','231':'ET','232':'ER','233':'EE','242':'FJ','246':'FI','250':'FR','262':'DJ','266':'GA','268':'GE',
    '276':'DE','288':'GH','300':'GR','320':'GT','324':'GN','332':'HT','340':'HN','344':'HK','348':'HU','352':'IS',
    '356':'IN','360':'ID','364':'IR','368':'IQ','372':'IE','376':'IL','380':'IT','384':'CI','388':'JM','392':'JP',
    '398':'KZ','400':'JO','404':'KE','408':'KP','410':'KR','414':'KW','417':'KG','418':'LA','422':'LB','426':'LS',
    '428':'LV','430':'LR','434':'LY','440':'LT','442':'LU','450':'MG','454':'MW','458':'MY','466':'ML','478':'MR',
    '484':'MX','496':'MN','498':'MD','499':'ME','504':'MA','508':'MZ','512':'OM','516':'NA','524':'NP','528':'NL',
    '540':'NC','548':'VU','554':'NZ','558':'NI','562':'NE','566':'NG','578':'NO','586':'PK','591':'PA','598':'PG',
    '600':'PY','604':'PE','608':'PH','616':'PL','620':'PT','634':'QA','642':'RO','643':'RU','646':'RW','682':'SA',
    '686':'SN','688':'RS','694':'SL','702':'SG','703':'SK','704':'VN','705':'SI','706':'SO','710':'ZA','716':'ZW',
    '724':'ES','728':'SS','729':'SD','740':'SR','752':'SE','756':'CH','760':'SY','762':'TJ','764':'TH','768':'TG',
    '784':'AE','788':'TN','792':'TR','795':'TM','800':'UG','804':'UA','807':'MK','818':'EG','826':'GB','834':'TZ',
    '840':'US','854':'BF','858':'UY','860':'UZ','862':'VE','887':'YE','894':'ZM',
};

function flagEmoji(id) {
    const a2 = ISO_NUM_TO_A2[id];
    if (!a2) return '';
    return a2.split('').map(c => String.fromCodePoint(0x1F1E6 + c.charCodeAt(0) - 65)).join('');
}

/* Inverse lookup so live news (which arrives as ISO alpha-2) can be mapped
   back to our numeric ids. */
const ISO_A2_TO_NUM = {};
for (const k in ISO_NUM_TO_A2) ISO_A2_TO_NUM[ISO_NUM_TO_A2[k]] = k;

/* GDELT (the live news source) tags articles with FIPS 10-4 country codes,
   which differ from ISO 3166-1 alpha-2 in a number of cases. */
const FIPS_TO_A2 = {
    AF:'AF',AG:'DZ',AJ:'AZ',AL:'AL',AM:'AM',AN:'AD',AO:'AO',AR:'AR',AS:'AU',AU:'AT',
    BA:'BH',BB:'BB',BD:'BM',BE:'BE',BG:'BD',BH:'BZ',BK:'BA',BL:'BO',BM:'MM',BN:'BJ',
    BO:'BY',BP:'SB',BR:'BR',BU:'BG',BX:'BN',BY:'BI',CA:'CA',CB:'KH',CD:'TD',CE:'LK',
    CF:'CG',CG:'CD',CH:'CN',CI:'CL',CM:'CM',CO:'CO',CS:'CR',CT:'CF',CU:'CU',CV:'CV',
    CY:'CY',DA:'DK',DJ:'DJ',DO:'DM',DR:'DO',EC:'EC',EG:'EG',EI:'IE',EK:'GQ',EN:'EE',
    ER:'ER',ES:'SV',ET:'ET',EZ:'CZ',FI:'FI',FJ:'FJ',FR:'FR',GB:'GA',GG:'GE',GH:'GH',
    GM:'DE',GR:'GR',GT:'GT',GV:'GN',GY:'GY',HA:'HT',HO:'HN',HR:'HR',HU:'HU',IC:'IS',
    ID:'ID',IN:'IN',IR:'IR',IS:'IL',IT:'IT',IV:'CI',JA:'JP',JM:'JM',JO:'JO',KE:'KE',
    KG:'KG',KN:'KP',KR:'KI',KS:'KR',KU:'KW',KZ:'KZ',LA:'LA',LE:'LB',LG:'LV',LH:'LT',
    LI:'LR',LO:'SK',LT:'LS',LU:'LU',LY:'LY',MA:'MG',MG:'MN',MI:'MW',MK:'MK',ML:'ML',
    MO:'MA',MP:'MU',MR:'MR',MT:'MT',MU:'OM',MX:'MX',MY:'MY',MZ:'MZ',NG:'NE',NH:'VU',
    NI:'NG',NL:'NL',NO:'NO',NP:'NP',NU:'NI',NZ:'NZ',PA:'PY',PE:'PE',PK:'PK',PL:'PL',
    PM:'PA',PO:'PT',QA:'QA',RO:'RO',RP:'PH',RS:'RU',RW:'RW',SA:'SA',SE:'SC',SF:'ZA',
    SG:'SN',SI:'SI',SL:'SL',SN:'SG',SO:'SO',SP:'ES',SU:'SD',SW:'SE',SY:'SY',SZ:'CH',
    TH:'TH',TI:'TJ',TO:'TG',TP:'ST',TS:'TN',TT:'TL',TU:'TR',TV:'TV',TW:'TW',TX:'TM',
    TZ:'TZ',UG:'UG',UK:'GB',UP:'UA',US:'US',UV:'BF',UY:'UY',UZ:'UZ',VC:'VC',VE:'VE',
    VM:'VN',WA:'NA',WS:'WS',WZ:'SZ',YE:'YE',YM:'YE',ZA:'ZM',ZI:'ZW',
};

/* Capital city per country — used by the live "Current" news feed. */
const CAPITALS = {
    '004':'Kabul','008':'Tirana','012':'Algiers','024':'Luanda','032':'Buenos Aires','036':'Canberra','040':'Vienna',
    '050':'Dhaka','051':'Yerevan','056':'Brussels','064':'Thimphu','068':'La Paz','070':'Sarajevo','072':'Gaborone',
    '076':'Brasília','090':'Honiara','100':'Sofia','104':'Naypyidaw','108':'Gitega','112':'Minsk','116':'Phnom Penh',
    '120':'Yaoundé','124':'Ottawa','140':'Bangui','144':'Colombo','148':"N'Djamena",'152':'Santiago','156':'Beijing',
    '158':'Taipei','170':'Bogotá','178':'Brazzaville','180':'Kinshasa','188':'San José','191':'Zagreb','192':'Havana',
    '196':'Nicosia','203':'Prague','208':'Copenhagen','214':'Santo Domingo','218':'Quito','222':'San Salvador',
    '231':'Addis Ababa','232':'Asmara','233':'Tallinn','242':'Suva','246':'Helsinki','250':'Paris','262':'Djibouti',
    '266':'Libreville','268':'Tbilisi','276':'Berlin','288':'Accra','300':'Athens','320':'Guatemala City','324':'Conakry',
    '332':'Port-au-Prince','340':'Tegucigalpa','344':'Hong Kong','348':'Budapest','352':'Reykjavík','356':'New Delhi',
    '360':'Jakarta','364':'Tehran','368':'Baghdad','372':'Dublin','376':'Jerusalem','380':'Rome','384':'Yamoussoukro',
    '388':'Kingston','392':'Tokyo','398':'Astana','400':'Amman','404':'Nairobi','408':'Pyongyang','410':'Seoul',
    '414':'Kuwait City','417':'Bishkek','418':'Vientiane','422':'Beirut','426':'Maseru','428':'Riga','430':'Monrovia',
    '434':'Tripoli','440':'Vilnius','442':'Luxembourg','450':'Antananarivo','454':'Lilongwe','458':'Kuala Lumpur',
    '466':'Bamako','478':'Nouakchott','484':'Mexico City','496':'Ulaanbaatar','498':'Chișinău','499':'Podgorica',
    '504':'Rabat','508':'Maputo','512':'Muscat','516':'Windhoek','524':'Kathmandu','528':'Amsterdam','540':'Nouméa',
    '548':'Port Vila','554':'Wellington','558':'Managua','562':'Niamey','566':'Abuja','578':'Oslo','586':'Islamabad',
    '591':'Panama City','598':'Port Moresby','600':'Asunción','604':'Lima','608':'Manila','616':'Warsaw','620':'Lisbon',
    '634':'Doha','642':'Bucharest','643':'Moscow','646':'Kigali','682':'Riyadh','686':'Dakar','688':'Belgrade',
    '694':'Freetown','702':'Singapore','703':'Bratislava','704':'Hanoi','705':'Ljubljana','706':'Mogadishu','710':'Pretoria',
    '716':'Harare','724':'Madrid','728':'Juba','729':'Khartoum','740':'Paramaribo','752':'Stockholm','756':'Bern',
    '760':'Damascus','762':'Dushanbe','764':'Bangkok','768':'Lomé','776':'Nukuʻalofa','780':'Port of Spain','784':'Abu Dhabi',
    '788':'Tunis','792':'Ankara','795':'Ashgabat','800':'Kampala','804':'Kyiv','807':'Skopje','818':'Cairo','826':'London',
    '834':'Dodoma','840':'Washington','854':'Ouagadougou','858':'Montevideo','860':'Tashkent','862':'Caracas','887':"Sana'a",
    '894':'Lusaka',
};
